cmake_minimum_required(VERSION 3.0)

set(MY_ADDITIONAL_SOURCES
    # Please add your source files here
)

set(ASSIGNMENT_SOURCES
    core/interpolate.cpp
    core/interpolate-impl.h
    core/interpolate.h
    core/random.cpp
    core/random.h
    rt/cameras/dofperspective.cpp
    rt/cameras/dofperspective.h
    rt/coordmappers/coordmapper.h
    rt/coordmappers/cylindrical.cpp
    rt/coordmappers/cylindrical.h
    rt/coordmappers/plane.cpp
    rt/coordmappers/plane.h
    rt/coordmappers/spherical.cpp
    rt/coordmappers/spherical.h
    rt/coordmappers/tmapper.cpp
    rt/coordmappers/tmapper.h
    rt/coordmappers/world.cpp
    rt/coordmappers/world.h
    rt/coordmappers/environment.cpp
    rt/coordmappers/environment.h
    rt/integrators/recraytrace.cpp
    rt/integrators/recraytrace.h
    rt/lights/arealight.cpp
    rt/lights/arealight.h
    rt/loaders/objmat.cpp
    rt/materials/lambertian.cpp
    rt/materials/lambertian.h
    rt/materials/phong.cpp
    rt/materials/phong.h
    rt/materials/cooktorrance.h
    rt/materials/cooktorrance.cpp
    rt/materials/mirror.cpp
    rt/materials/mirror.h
    rt/materials/combine.cpp
    rt/materials/combine.h
    rt/materials/flatmaterial.cpp
    rt/materials/flatmaterial.h
    rt/materials/fuzzymirror.cpp
    rt/materials/fuzzymirror.h
    rt/materials/glass.cpp
    rt/materials/glass.h
    rt/solids/striangle.cpp
    rt/solids/striangle.h
    rt/textures/texture.h
    rt/textures/constant.cpp
    rt/textures/constant.h
    rt/textures/checkerboard.cpp
    rt/textures/checkerboard.h
    rt/textures/imagetex.cpp
    rt/textures/imagetex.h
    rt/textures/perlin.cpp
    rt/textures/perlin.h
    ${MY_ADDITIONAL_SOURCES}
    main/a_materials.cpp
    main/a_textures.cpp
    main/a_local.cpp
    main/a_mappers.cpp
    main/a_distributed.cpp
    main/a_smooth.cpp
    main/a_renderingcompetition.cpp
    main/a_scene.cpp
    rt/solids/environment.cpp
    rt/solids/environment.h

)

file(COPY
    models/bread_french.obj         
    models/fl3.obj                 
    models/bread_french_spec.png    
    models/glass_empty_filled.mtl  
    models/vase.mtl
    models/bread_french_Text.png    
    models/glass_empty_filled.obj  
    models/vase.obj
    models/stones_bump.png         
    models/wall2.mtl
    models/stones_diffuse.png      
    models/wall2.obj
    models/fl1.mtl                  
    models/stones_spec.png         
    models/wall.mtl
    models/fl1.obj                  
    models/teapot_2obj.mtl         
    models/wall.obj
    models/fl2.mtl                  
    models/teapot_2obj.obj         
    models/wooden_table.mtl
    models/fl2.obj                  
    models/teapot_baseColor.png    
    models/wooden_table.obj
    models/table_bot.png
    models/table_top.png
    models/Bread.png
    models/cuttingboard_base_normal.png
    models/cuttingboard_base_text.png
    models/cuttingboard_top_normal.png
    models/cuttingboard_top_text.png
    models/vetvicka_bobule_albedo.png
    models/Diffuse_Roughness.png
    models/linka01_DiffuseMap.png

    DESTINATION ${CMAKE_BINARY_DIR}/models
)
